# Generated by Django 5.0.2 on 2024-03-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneToMany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
